server:
  port: 8085
spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${USERNAME}" password="${PASSWORD}";
    producer:
      group-id: $Default
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
topic:
  name: balance_check_command
